import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Open Check FUNCoder",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja">
      <head>
        <meta charSet="UTF-8" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className="bg-gray-900">
        <header></header>
        <main>
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  )
}